name: Docker Image CI

on:
  push:
    branches: none # [ "main" ]
  pull_request:
    branches: none # [ "main" ]

  # Allows you to run this workflow manually from the Action Tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag testimage-dockergit:$(date +%s)
